parameters:
    # Blogger contact email address
    blogger_blog.emails.contact_email: ndenc2+symblogwebmaster@gmail.com
    # Blogger max latest comments
    blogger_blog.comments.latest_comment_limit: 10
